shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

# Syntax highlighting must be loaded last
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"
